debug: false
discord:
    token: null
    max_length: 300
database:
    connection: sqlite
    host: localhost
    port: 3306
    user: root
    password: password
    database: bot.db
redis:
    host: localhost
    port: 6379
    db: 0
    passwd: null
engine_enabled:
    aquestalk1: false
    aquestalk2: false
    aquestalk10: false
    voicevox: true
voicevox:
    edition:
        core: true
        engine: false
    url: http://localhost:50021
dev_key:
    aqkanji2koe: null
    aquestalk10: null
